"""Public PRISM command-line shell."""

from .main import (
    PrismAPIProtocol,
    build_parser,
    handle_add_material,
    handle_adjudication_history,
    handle_cases,
    handle_compare,
    handle_discover,
    handle_fetch,
    handle_fetch_all,
    handle_follow_up,
    handle_ingest,
    handle_rebuild_report,
    handle_report,
    handle_report_version,
    handle_report_versions,
    handle_research,
    handle_search,
    handle_snapshot,
    handle_state,
    handle_timeline,
    main,
)

__all__ = [
    "PrismAPIProtocol",
    "build_parser",
    "handle_add_material",
    "handle_adjudication_history",
    "handle_cases",
    "handle_compare",
    "handle_discover",
    "handle_fetch",
    "handle_fetch_all",
    "handle_follow_up",
    "handle_ingest",
    "handle_rebuild_report",
    "handle_report",
    "handle_report_version",
    "handle_report_versions",
    "handle_research",
    "handle_search",
    "handle_snapshot",
    "handle_state",
    "handle_timeline",
    "main",
]
