"""Browser-upload staging seam for the PRISM material workbench (WB-1).

This module is the WebUI's input adapter for real browser uploads.  It
never writes the corpus, never calls an LLM and never touches SQLite: the
bytes a browser sends are validated here (suffix whitelist, non-empty
payload, configurable size cap enforced WHILE the event content is read,
in bounded blocks, so an oversized upload is refused long before its
bytes are fully materialized), spooled into a staging directory that must
live inside ``PRISM_HOME`` (or an explicitly declared controlled root)
under a server-generated unguessable ``upload_id`` — the client filename
is kept as display/metadata only and never reaches the filesystem as a
path — and then handed to the one and only write path,
``PrismAPI.add_material`` (the automatic pipeline stays the exclusive
corpus/graph writer).  The staged file is removed once the pipeline has
taken the material over; PRISM's raw retention remains the ingestion
pipeline's own ``raw/`` copy, not this staging area.  ``discard`` and the
``submit`` provenance gate (:meth:`UploadStagingService.verify`) only
ever accept objects this very service issued inside the validated staging
root — a hand-crafted or tampered :class:`StagedUpload` is refused before
it can delete anything or reach ingestion.

Everything here is dependency-free and NiceGUI-free: the page passes in
the upload event's name/bytes, tests pass in plain values.  Validation
failures raise before any facade call, and a facade failure propagates
unchanged — this seam never returns a fake success.
"""

from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Protocol
from uuid import uuid4

from .evidence import parse_time_bound
from .materials import _validated_target_case

#: Accepted upload suffixes — the same whitelist as the path intake.
UPLOAD_SUFFIXES = (".md", ".markdown", ".pdf")

#: Default per-file upload cap (WB-1.4 suggests 50 MB).
DEFAULT_MAX_UPLOAD_BYTES = 50 * 1024 * 1024

#: Read block for bounded upload-event reads: the reader stops within one
#: block of the cap, so peak memory stays near the cap instead of the
#: full upload size.
_READ_BLOCK_BYTES = 64 * 1024

#: Metadata key recording where an uploaded material came from.
UPLOAD_ORIGIN = "prism-webui"


@dataclass(frozen=True, slots=True)
class StagedUpload:
    """One validated upload spooled under a server-generated name."""

    upload_id: str
    path: Path
    original_name: str
    suffix: str
    size_bytes: int
    sha256: str

    def __post_init__(self) -> None:
        for name in ("upload_id", "original_name"):
            value = getattr(self, name)
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"{name} must be a non-empty string")
        if not isinstance(self.path, Path):
            raise TypeError("path must be a Path")
        if self.suffix not in UPLOAD_SUFFIXES:
            raise ValueError("suffix must be one of the allowed upload types")
        if isinstance(self.size_bytes, bool) or not isinstance(
            self.size_bytes, int
        ):
            raise TypeError("size_bytes must be an int")
        if self.size_bytes <= 0:
            raise ValueError("size_bytes must be positive")
        digest = self.sha256
        if (
            not isinstance(digest, str)
            or len(digest) != 64
            or any(character not in "0123456789abcdef" for character in digest)
        ):
            raise ValueError("sha256 must be a 64-character hex digest")

    def metadata(self) -> dict[str, Any]:
        """The audit metadata preserved alongside the material (WB-1.3)."""
        return {
            "upload_origin": UPLOAD_ORIGIN,
            "upload_original_name": self.original_name,
            "upload_sha256": self.sha256,
            "upload_size_bytes": self.size_bytes,
        }


class UploadStagingService:
    """Spool validated upload bytes into the PRISM-controlled staging area.

    The staging root lives under ``PRISM_HOME`` (the caller supplies it —
    possibly lazily through a provider, because the runtime resolves only
    at startup) and is validated on every use against the controlled root
    (``PRISM_HOME`` by default, or an explicitly declared one): it must be
    a proper subdirectory of it, with fixed directory names never derived
    from request data.  Each upload lands in its own
    ``<staging_root>/<upload_id>/source.<ext>`` directory: the file name is
    generated by the server, the write happens through a temporary file
    and an atomic :func:`os.replace` (readers never observe a partial
    upload), and the SHA-256/size recorded on :class:`StagedUpload` are
    recomputed from the received bytes as audit metadata.  The service
    remembers every :class:`StagedUpload` it issued, so :meth:`discard`
    and :meth:`verify` can refuse anything it did not generate itself.
    """

    def __init__(
        self,
        staging_root: Path | Callable[[], Path],
        *,
        max_upload_bytes: int = DEFAULT_MAX_UPLOAD_BYTES,
        controlled_root: Path | Callable[[], Path] | None = None,
    ) -> None:
        if callable(staging_root):
            self._root_provider = staging_root
        elif isinstance(staging_root, Path):
            self._root_provider = lambda: staging_root
        else:
            raise TypeError("staging_root must be a Path or a Path provider")
        if controlled_root is None:
            self._controlled_provider = _default_controlled_root
        elif callable(controlled_root) and not isinstance(
            controlled_root, Path
        ):
            self._controlled_provider = controlled_root
        elif isinstance(controlled_root, Path):
            self._controlled_provider = lambda: controlled_root
        else:
            raise TypeError(
                "controlled_root must be a Path, a Path provider or None"
            )
        if isinstance(max_upload_bytes, bool) or not isinstance(
            max_upload_bytes, int
        ):
            raise TypeError("max_upload_bytes must be an int")
        if max_upload_bytes <= 0:
            raise ValueError("max_upload_bytes must be positive")
        self._max_upload_bytes = max_upload_bytes
        # upload_id -> the exact StagedUpload record this service issued.
        self._issued: dict[str, StagedUpload] = {}

    @property
    def max_upload_bytes(self) -> int:
        """The configured per-file cap (also bounds event reads)."""
        return self._max_upload_bytes

    def _root(self) -> Path:
        root = self._root_provider()
        if not isinstance(root, Path):
            raise TypeError("staging root provider must return a Path")
        return root

    def _controlled(self) -> Path:
        controlled = self._controlled_provider()
        if not isinstance(controlled, Path):
            raise TypeError("controlled root provider must return a Path")
        return controlled

    def _validated_root(self) -> Path:
        """Resolve and validate the staging root before anything is written.

        The staging root must be a proper subdirectory of the controlled
        root (``PRISM_HOME`` by default).  The refusal carries no
        filesystem paths so it stays safe to surface in the UI.
        """
        root = self._root().expanduser().resolve()
        controlled = self._controlled().expanduser().resolve()
        if root == controlled or not root.is_relative_to(controlled):
            raise ValueError(
                "staging root must be a subdirectory of the controlled "
                "root (PRISM_HOME by default); refusing to stage outside it"
            )
        return root

    def stage(self, filename: str, data: bytes | bytearray) -> StagedUpload:
        """Validate and spool one upload; refusals raise before any write."""
        if not isinstance(filename, str):
            raise TypeError("filename must be a string")
        if not filename.strip():
            raise ValueError("filename must be a non-empty string")
        if isinstance(data, bytearray):
            payload = bytes(data)
        elif isinstance(data, bytes):
            payload = data
        else:
            raise TypeError("upload data must be bytes")
        # The client name is display metadata only: strip every path
        # component it may carry and never use it to build a disk path.
        original_name = Path(filename.replace("\\", "/")).name
        if not original_name.strip():
            raise ValueError("filename must contain a file name")
        suffix = Path(original_name).suffix.lower()
        if suffix not in UPLOAD_SUFFIXES:
            allowed = ", ".join(UPLOAD_SUFFIXES)
            raise ValueError(
                f"unsupported file type; only Markdown and PDF uploads are "
                f"accepted ({allowed})"
            )
        if not payload.strip():
            raise ValueError("uploaded file is empty")
        if len(payload) > self._max_upload_bytes:
            raise ValueError(
                f"uploaded file exceeds the {self._max_upload_bytes} byte "
                "limit"
            )
        upload_id = uuid4().hex
        directory = self._validated_root() / upload_id
        destination = directory / f"source{suffix}"
        # Defense in depth: the generated name cannot traverse, but the
        # resolved destination is still required to stay inside the upload
        # directory before anything is written.
        if not destination.resolve().is_relative_to(directory.resolve()):
            raise ValueError("staged path escapes its upload directory")
        staging = directory / f".{destination.name}.{os.getpid()}.tmp"
        try:
            directory.mkdir(parents=True, exist_ok=True)
            with staging.open("wb") as handle:
                handle.write(payload)
            os.replace(staging, destination)
        except BaseException:
            staging.unlink(missing_ok=True)
            raise
        staged = StagedUpload(
            upload_id=upload_id,
            path=destination,
            original_name=original_name,
            suffix=suffix,
            size_bytes=len(payload),
            sha256=hashlib.sha256(payload).hexdigest(),
        )
        self._issued[upload_id] = staged
        return staged

    def verify(self, staged: StagedUpload) -> None:
        """Refuse any staged upload this service did not issue unchanged.

        :meth:`UploadController.submit` calls this BEFORE any facade call:
        the upload id must be one this very service issued, every recorded
        field (path, original name, suffix, size, digest) must still match
        the issuance, the resolved path must still live inside the
        currently validated staging root, and the bytes on disk must still
        match the recorded size and SHA-256 — a hand-crafted or tampered
        :class:`StagedUpload` therefore never reaches ingestion.  The
        refusals carry no filesystem paths so they stay safe to surface in
        the UI.
        """
        if not isinstance(staged, StagedUpload):
            raise TypeError("staged must be a StagedUpload")
        issued = self._issued.get(staged.upload_id)
        if issued is None or issued != staged:
            raise ValueError(
                "refusing to submit an upload this service did not stage: "
                f"{staged.upload_id}"
            )
        root = self._validated_root()
        resolved = staged.path.expanduser().resolve()
        if (
            resolved != issued.path.expanduser().resolve()
            or not resolved.is_relative_to(root)
        ):
            raise ValueError(
                "staged upload no longer lives inside the staging root: "
                f"{staged.upload_id}"
            )
        if not resolved.is_file():
            raise FileNotFoundError(
                f"staged upload is no longer available: {staged.original_name}"
            )
        if resolved.stat().st_size != staged.size_bytes:
            raise ValueError(
                "staged upload no longer matches its recorded size: "
                f"{staged.upload_id}"
            )
        digest = hashlib.sha256()
        with resolved.open("rb") as handle:
            for block in iter(
                lambda: handle.read(_READ_BLOCK_BYTES), b""
            ):
                digest.update(block)
        if digest.hexdigest() != staged.sha256:
            raise ValueError(
                "staged upload content no longer matches its recorded "
                f"digest: {staged.upload_id}"
            )

    def discard(self, staged: StagedUpload) -> None:
        """Remove one staged upload; best effort and idempotent.

        Only uploads this very service issued — field for field — are ever
        deleted: a :class:`StagedUpload` built anywhere else, or one whose
        recorded fields were tampered with, is refused, so the call can
        never become an arbitrary-path deletion primitive.
        """
        if not isinstance(staged, StagedUpload):
            raise TypeError("staged must be a StagedUpload")
        issued = self._issued.get(staged.upload_id)
        if issued is None or issued != staged:
            raise ValueError(
                "refusing to discard an upload this service did not stage: "
                f"{staged.upload_id}"
            )
        staged.path.unlink(missing_ok=True)
        try:
            staged.path.parent.rmdir()
        except OSError:
            pass


def _default_controlled_root() -> Path:
    """The default controlled root anchoring the staging area: PRISM_HOME."""
    from prism.config import PathConfig

    return PathConfig.prism_home()


class UploadEntryFacade(Protocol):
    """The facade operations used by the browser upload flow."""

    async def add_material(
        self,
        source: object,
        target_case: object,
        metadata: dict[str, Any] | None = None,
        *,
        as_of: datetime | None = ...,
        use_llm: bool = ...,
        parent_debate_run_id: str | None = ...,
    ) -> object: ...

    async def case_overviews(self, **filters: object) -> object: ...


class UploadController:
    """View-model adapter from browser upload events to ``add_material``.

    ``stage`` validates and spools the bytes an upload event carried;
    ``submit`` appends one already-staged upload to one declared target
    case through the facade (validating the case and the optional
    ``as_of``/``use_llm``/parent-run arguments exactly like the path
    intake, before any facade call); ``upload`` is the end-to-end
    convenience over both.  The staged file is cleaned up once the facade
    call has finished — on success and on failure alike, because the
    pipeline's own raw/corpus copies (or its audited failure) are the
    authoritative outcome of the append.
    """

    def __init__(self, api: UploadEntryFacade, staging: UploadStagingService):
        if not callable(getattr(api, "add_material", None)):
            raise TypeError("api must provide add_material()")
        if not isinstance(staging, UploadStagingService):
            raise TypeError("staging must be an UploadStagingService")
        self._api = api
        self._staging = staging

    def stage(self, filename: str, data: bytes | bytearray) -> StagedUpload:
        """Validate and spool one upload (delegates to the staging service)."""
        return self._staging.stage(filename, data)

    def discard(self, staged: StagedUpload) -> None:
        """Discard one staged upload (delegates to the staging service)."""
        self._staging.discard(staged)

    def read_event(self, event: object) -> tuple[str, bytes]:
        """Read one upload event's name/bytes within the staging size cap.

        The cap binds while the event content is read (bounded blocks,
        never an unbounded ``read()``), so an oversized upload is refused
        before its bytes are fully materialized in memory (WB-1.4).
        """
        return read_upload_event(event, self._staging.max_upload_bytes)

    async def submit(
        self,
        staged: StagedUpload,
        target_case: object,
        *,
        as_of: datetime | str | None = None,
        use_llm: bool = False,
        parent_debate_run_id: str | None = None,
    ) -> dict[str, Any]:
        """Append one staged upload to one declared case, end to end.

        The staged upload is verified FIRST — issued by this very staging
        service, still inside the validated staging root, bytes still
        matching the recorded size/digest — so a forged or tampered
        :class:`StagedUpload` is refused before anything (validation or
        facade) runs and never reaches ingestion.
        """
        if not isinstance(staged, StagedUpload):
            raise TypeError("staged must be a StagedUpload")
        self._staging.verify(staged)
        resolved_case = _validated_target_case(target_case)
        cutoff = (
            parse_time_bound("as_of", as_of) if as_of is not None else None
        )
        if not isinstance(use_llm, bool):
            raise TypeError("use_llm must be a bool")
        if parent_debate_run_id is not None:
            if (
                not isinstance(parent_debate_run_id, str)
                or not parent_debate_run_id.strip()
            ):
                raise ValueError(
                    "parent_debate_run_id must be a non-empty string "
                    "when supplied"
                )
            parent_debate_run_id = parent_debate_run_id.strip()
        try:
            result = await self._api.add_material(
                staged.path,
                resolved_case,
                staged.metadata(),
                as_of=cutoff,
                use_llm=use_llm,
                parent_debate_run_id=parent_debate_run_id,
            )
        finally:
            self._staging.discard(staged)
        from .materials import outcome_view

        view = outcome_view(result)
        view["upload"] = {
            "upload_id": staged.upload_id,
            "original_name": staged.original_name,
            "size_bytes": staged.size_bytes,
            "sha256": staged.sha256,
        }
        return view

    async def upload(
        self,
        filename: str,
        data: bytes | bytearray,
        target_case: object,
        *,
        as_of: datetime | str | None = None,
        use_llm: bool = False,
        parent_debate_run_id: str | None = None,
    ) -> dict[str, Any]:
        """Stage then submit one browser upload in a single call."""
        staged = self.stage(filename, data)
        return await self.submit(
            staged,
            target_case,
            as_of=as_of,
            use_llm=use_llm,
            parent_debate_run_id=parent_debate_run_id,
        )

    async def load_case_options(self) -> dict[str, str]:
        """The recorded cases a browser upload may target (H-3: select only).

        Keys are case ids and values are display labels; the page offers
        exactly these options — no free-text case entry, no guessing.
        """
        overviews_getter = getattr(self._api, "case_overviews", None)
        if not callable(overviews_getter):
            raise ValueError(
                "case_overviews is required to list selectable target cases"
            )
        overviews = tuple(await overviews_getter())
        options: dict[str, str] = {}
        for overview in overviews:
            case_id = getattr(overview, "case_id", None)
            if not isinstance(case_id, str) or not case_id.strip():
                continue
            name = getattr(overview, "name", None)
            label = f"{case_id} — {name}" if isinstance(name, str) and name.strip() else case_id
            options[case_id] = label
        return options


def read_upload_event(
    event: object, max_bytes: int | None = None
) -> tuple[str, bytes]:
    """Extract ``(filename, bytes)`` from one NiceGUI upload event.

    The event object is duck-typed (``name`` plus a readable ``content``),
    so the page seam and its tests share one adapter instead of the page
    handling NiceGUI types itself.  The content is read in bounded blocks
    of :data:`_READ_BLOCK_BYTES` and the read stops — with a
    ``ValueError`` naming the limit — as soon as the accumulated size
    exceeds ``max_bytes`` (default: the WB-1.4 cap), so a huge upload is
    refused without ever being fully materialized in memory.
    """
    if max_bytes is None:
        max_bytes = DEFAULT_MAX_UPLOAD_BYTES
    if isinstance(max_bytes, bool) or not isinstance(max_bytes, int):
        raise TypeError("max_bytes must be an int")
    if max_bytes <= 0:
        raise ValueError("max_bytes must be positive")
    if not hasattr(event, "name") or not hasattr(event, "content"):
        raise TypeError("upload event must carry a name and readable content")
    name = getattr(event, "name", None)
    content = getattr(event, "content", None)
    if not isinstance(name, str) or not name.strip():
        raise ValueError("upload event carried no file name")
    if not hasattr(content, "read"):
        raise TypeError("upload event carried no readable content")
    blocks: list[bytes] = []
    total = 0
    while True:
        block = content.read(_READ_BLOCK_BYTES)
        if not isinstance(block, (bytes, bytearray)):
            raise TypeError("upload event content did not yield bytes")
        if not block:
            break
        blocks.append(bytes(block))
        total += len(block)
        if total > max_bytes:
            raise ValueError(
                f"uploaded file exceeds the {max_bytes} byte limit"
            )
    return name, b"".join(blocks)


__all__ = [
    "DEFAULT_MAX_UPLOAD_BYTES",
    "StagedUpload",
    "UPLOAD_ORIGIN",
    "UPLOAD_SUFFIXES",
    "UploadController",
    "UploadEntryFacade",
    "UploadStagingService",
    "read_upload_event",
]
